moneydays/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^$', 'SaveMoney.views.home_page', name='home'),
                       url(r'calculate/$',
                           'SaveMoney.views.result_page',
                           name='calculate'),
                      )

SaveMoney/models.py
from django.db import models


class Item(models.Model):   
    goal = models.TextField(default='')
    money = models.FloatField(default=0)
    time = models.IntegerField(default=0)
    rate = models.FloatField(default=0)

SaveMoney/views.py
from django.shortcuts import redirect, render
from django.db import reset_queries
from SaveMoney.models import Item
import operator

def home_page(request):
    if(request.method == 'POST'and request.POST.get(
                                   'button_cal','') == 'calculate'):
        Item.objects.all().delete() #delete database
        goal_text = request.POST['goal']
        money_text = float(request.POST['money'])
        time_text = int(request.POST['time'])
        rate_text = float(request.POST['rate'])
        Item.objects.create(
                goal = goal_text,
                money = money_text,
                time = time_text,
                rate = rate_text
               )
        reset_queries()
        return redirect('/calculate/')
    items = Item.objects.all()

    return render(request, 'home.html')

# calculate
def result_page(request):
    Rate_total = 0
    Rate = 0
    Money = 0
    data_time = 0
    data_money = 0
    data_rate = 0
    all_money = []
    all_rate = []
    all_time = []
    items = Item.objects.all()
    for i in items:
        Money = i.money
        for num in range(0,i.time):
            Rate = float(i.rate)*float(Money)/100
            Money = float(Money) + float(Rate)
            Rate_total = float(Rate_total)+float(Rate)
            all_money.append(Money)
            all_rate.append(Rate_total)
            all_time.append(num)

    if(request.method == 'POST' and request.POST.get(
       'Home_send', '') == 'send'):
        return redirect('/')

    return render(request, 'calculate.html',
                  {'items':items,'total_money':Money,
                   'total_rate':Rate_total, 'all_times':all_time,
                   'all_moneys':all_money,'all_rates':all_rate})


def TotalMoney(year, money, rate):
    Rate_All = 0
    for num in range(0,year):
        Rate = float(rate)*float(money)/100
        money = float(money) + float(Rate)
        Rate_All = float(Rate_All)+float(Rate)
    return (money,Rate_All)
    #all_money, all_rate = TotalMoney(items.year,items.money,items.rate)

SaveMoney/templates/calculate.html
<html>
    <meta http-equiv=Content-Type content=text/html;charset=utf-8 >
    <head>
        <title>Saving Money Every Day</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'SaveMoney/style1.css' %}" />
    </head>
    <body>
        <img src="http://www.friendskorner.com/forum/photopost/data/500/welcome20with20animated20white20dov1.gif" alt="welcome" style="width:491;height210" align="left"><div id="box0">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<h1>Save money on everyday</h1></div>

<!--Text-->
        <div id="box1" style="left:1150px; top:21px"><br><br><br><br><br><br><br>
           <text1>&nbsp;&nbsp;&nbsp;มีสลึงพึงบรรจบให้ครบบาท<br>&nbsp;&nbsp;&nbsp;&nbsp;อย่าให้ขาดสิ่งของต้องประสงค์<br></text1>
        </div>
<!--end text-->


<!--result-->
        <div id="box2" style="left:500px; top:150px"><br><br><br><br><br><br><br>
        <table id="id_list_table" align="center">
           <tr><td><text0>เป้าหมายการออม: {% for item in items %}{{ item.goal }}{% endfor %}</text0></td></tr>
           <tr><td><text0>เงินออมทั้งหมด: {{ total_money }}</text0></td></tr>
           <tr><td><text0>ดอกเบี้ย: {{ total_rate }}</text0></td></tr>
        </table><br><br>
        <form method="POST"><text0>
            <center><INPUT Type="submit" VALUE="home" id="button" >
            <INPUT Type = "hidden" value = "send" name = "Home_send"></center>
            {% csrf_token %}</text0>
        </form>
        </div>
        <!--div id="box3"--><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <table id="id_money_table">
        <tbody>
           <tr><th>ระยะเวลา</th>
               {% for time in all_times %}
               <td><text0>{{time}}</text0></td>
               {% endfor %}
               <td><text0>{% for item in items %}{{ item.time }}{% endfor %}</text0></td>
               </tr>
           <tr><th>จำนวนเงินออม</th>
               <td><text0>{% for item in items %}{{ item.money }}{% endfor %}</text0></td>
               {% for money in all_moneys %}
               <td><text0>{{money}}</text0></td>
               {% endfor %}
               </tr>
           <tr><th>ดอกเบี้ย</th>
               <td><text0>{% for item in items %}{{ item.rate }}{% endfor %}</text0></td>
               {% for rate in all_rates %}
               <td><text0>{{rate}}</text0></td>
               {% endfor %}
               </tr>
        </table>
<!--end result-->

<!--Text-->
        <div id="box1" style="left:1024px; top:250px"><br><br><br><br><br><br><br>
           <text1>
            &nbsp;&nbsp;&nbsp;จงมักน้อยกินน้อยค่อยบรรจง<br>&nbsp;&nbsp;&nbsp;&nbsp;อย่าจ่ายลงให้มากจะยากนาน<br><br></text1>
           <text2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- สุภาษิตสอนหญิง (สุนทรภู่) -</text2>
        </div>
<!--Text-->
    </body>
</html>

SaveMoney/templates/home.html
<html>
    <meta http-equiv=Content-Type content=text/html;charset=utf-8 >
    <head>
        <title>Saving Money Every Day</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'SaveMoney/style1.css' %}" />
    </head>
    <body>
        <img src="http://www.friendskorner.com/forum/photopost/data/500/welcome20with20animated20white20dov1.gif" alt="welcome" style="width:491;height210" align="left"><div id="box0">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<h1>Save money on everyday</h1></div>
        <!--div id="box0"><br><br><h1>Welcome Save money on everyday</h1></div-->

<!--Text-->
        <div id="box1" style="left:1300px; top:21px"><br><br><br><br><br><br><br>
           <p id="date"></p>
           <script>
               var d = new Date();
               var n = d.toDateString();
               var c = d.toLocaleTimeString();
               document.getElementById("date").innerHTML = n+"  "+c;
               /*document.write(d.toLocaleTimeString());*/
           </script>
           <text1>&nbsp;&nbsp;&nbsp;มีสลึงพึงบรรจบให้ครบบาท<br>&nbsp;&nbsp;&nbsp;&nbsp;อย่าให้ขาดสิ่งของต้องประสงค์<br></text1>
        </div>
<!--end text-->

<!--input value-->
        <div id="box2" style="left:500px; top:200px"><br><br><br><br><br><br><br>
        <form method="POST"><text0>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;เป้าหมายการออม:<input name="goal" id="id_goal" placeholder="Enter your goal" size="20"/><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; จำนวนเงินออม: <input name="money" id="id_money" placeholder="Money" size="5"/> บาท ต่อ เดือน<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ระยะเวลาการออม: <input name="time" id="id_time" placeholder="Time" size="5"/> ปี<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ดอกเบี้ยเงินฝาก: <input name="rate" id="id_rate" placeholder="Rate" size="5"/> ต่อ ปี <br><br>
            <center><INPUT Type="submit" VALUE="calculate" id="button" >
            <INPUT Type = "hidden" value = "calculate" name = "button_cal">
            <!--input type="image" src="img_submit.gif" alt="Submit" width="48" height="48"style="float:left;"-->

            <INPUT TYPE=RESET onClick="return confirm('Are you sure you want to reset the form?')"></center>
            {% csrf_token %}</text0>
        </form>
        </div>
<!--end input-->

<!--Text-->
        <div id="box1" style="left:1180px; top:280px"><br><br><br><br><br><br><br>
           <text1>
            &nbsp;&nbsp;&nbsp;จงมักน้อยกินน้อยค่อยบรรจง<br>&nbsp;&nbsp;&nbsp;&nbsp;อย่าจ่ายลงให้มากจะยากนาน<br><br></text1>
           <text2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- สุภาษิตสอนหญิง (สุนทรภู่) -</text2>
        </div>
<!--Text-->
        <a href="{% url 'SaveMoney.views.result_page' %}">
            <img src="http://www.cse.iitb.ac.in/~gauravloj/images/back-button.png" alt="back" style="width:60px;height:59px" align="left">
        </a>
    </body>
</html>